### ISSUE TITLE
SofVwave3 >> SofVwaveI

### ISSUE THREAD

**Issue by kkoetje** [Coastal-Imaging-Research-Network/Video-Currents-Toolbox#4]
All branches of videoCurrentGen.m appear to have a typo in line 138 where SofVwave3 should be replaced with SofVwaveI (that's an upper case i at the end, not a lower case L). I believe @melissarmoulton addressed this in her demo version of the function.

**Comment by eswanson-usgs** [comment]
This has been resolved in all current branches with videoCurrentGen.m
